### ISSUE TITLE
Name conflicts with Peter Miller's build tool "cook"

### ISSUE THREAD

**Issue by wnoise** [jachris/cook#1]
While his website is down after his death, the source is still on FTP sites, and it's available as Debian and Ubuntu packages.

**Comment by jachris** [comment]
Thank you for submitting the issue.
Yes, it seems like there is a name conflict. Not sure if and how to solve it though.
What would you recommend?

**Comment by wnoise** [comment]
Well, the two options are renaming, or accepting the conflict.

**Comment by jachris** [comment]
Closing this for now. If someone thinks this is an issue, please reopen.
