### ISSUE TITLE
flake8: F821 undefined name 'primaries'

### ISSUE THREAD

**Issue by cclauss** [jachris/cook#2]
flake8 testing of https://github.com/jachris/cook on Python 3.6.2

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./cook/core/graph.py:327:23: F821 undefined name 'primaries'
    return primary in primaries
                      ^
```

**Comment by jachris** [comment]
Thank you, this was fixed with commit 941442f.
