### ISSUE TITLE
immediate quit whole build if any job fails

### ISSUE THREAD

**Issue by velkyel** [jachris/cook#24]
cmdline switch at least would be fine.  Especially on Windows (git bash console) it's annoying to stop failing build process.

**Comment by jachris** [comment]
You are totally right. Not sure how I could miss this... I will add it next week, currently busy with university. Also, I have to see if we can improve the current behaviour when issuing Ctrl+C. Currently it justs crashes the programm more or less. We can let it shut down gracefully and save current process...

Also, I think a flag is more appropriate since I consider continuation after failure a feature. But maybe we can invert the default setting...

I'll ping this thread after making progess.

**Comment by jachris** [comment]
Okay, so I did a rough implementation of what we have discussed.

d78de78 implements handling of Ctrl+C during build. The build will be stopped, all current tasks killed and current progress will be saved.

bfc4292 adds the `-f` or `--fastfail` option to the command-line interface. If being set and a task fails, all other tasks will be killed and the current progress will be saved.

Is this what you were looking for? The implementation is not very good right now (i.e. error messages) but it does the job and can be improved soon.

-----

Edit: I just noticed there are some UI issues going on when using bash on windows. Will have to investigate. In the meantime, cmd.exe should work fine.

**Comment by velkyel** [comment]
thank you very much.  closing.

**Comment by velkyel** [comment]
When task fails (and option --fastfail is enabled) error messages about failing other tasks are annoying and user have to scroll terminal and find what really fails first.

**Comment by jachris** [comment]
I will solve this during the next few days.

**Comment by jachris** [comment]
Actually I could not resist to already make some minor adjustments.

I want to solve this properly: Currently subprocesses (invoked by `core.call`) receive the `Ctrl+C` as well. Pull request #26 should change this behaviour. Only the main process should receive it. While this may seem only tangential to this issue, it is required to ensure that no messages regarding failed tasks are printed when using `Ctrl+C`. It also replaces the error messages in favor for a simple `Aborting <XY> tasks`. You can try it out if you want, but **it might not work on Windows**. I will test that soon.

**Comment by velkyel** [comment]
no rush, enjoy New Year.

**Comment by jachris** [comment]
Yes, I hope you did as well.
I merged the PR after making sure that it works on Windows.
