### ISSUE TITLE
decider option like scons

### ISSUE THREAD

**Issue by velkyel** [jachris/cook#27]
It would be nice to have something like Decider function ( http://scons.org/doc/HTML/scons-user.html#idm139933297217568 ) - so manage when input file has changed.  As part of my build process is binary mesh builder file and I'd like to rebuild every time its checksum changed and not timestep.

**Comment by jachris** [comment]
I need some more information: The input we are talking about (the one you would like to be hashed) is created as an output of another rule, right? Or is it just an ordinary file? And why do you need Hashing – does the timestamp not change and you want to rebuild or does the content not change and you want to avoid rebuilding?

**Comment by velkyel** [comment]
It's ordinary file, respectively it's output of completely another build process.  And I want to avoid rebuild if its timestamp is changed, and rebuild if checksum is changed only. so in example:
```
@core.rule
def build_mesh(input, output):
   input = core.source(input)
   output = core.build(output)
   yield core.publish(phony=False, inputs=[input, geometry_binary], message='Building {}'.format(output))
   convert(input, output)
```
I'd like to rebuild if checksum geometry_binary is changed.  For start it would be enough to add global "decider" switch (for example core variable).

edit: python formatting

**Comment by jachris** [comment]
Alright, in that case you can already do something like this:

```python
from cook import core

converter = core.source('converter.exe')

@core.cache
def hash_file(path):
   with open(path, 'rb') as stream:
       return core.checksum(stream.read())

@core.rule
def build_mesh(input, output):
    input = core.source(input)
    output = core.build(output)
    yield core.publish(
        inputs=[input], 
        message='Building {}'.format(output),
        outputs=[output],
        check=hash_file(converter)
    )
    convert(input, output)

build_mesh('test.obj', 'test.bin')
```

The `check` parameter of `core.publish` can contain almost any object and automatically checks for changes. So if `hash_file(converter)` changes, then the rule will be rebuilt. I decorated `hash_file` with `@core.cache`, so that multiple uses of the same file will only hash it once.

_(Note: You don't have to pass `phony=False`, this is the default.)_

**Comment by velkyel** [comment]
great.  this technique works for me, thanks.
