### ISSUE TITLE
Cook name duplicates established work of art

### ISSUE THREAD

**Issue by bovine** [jachris/cook#28]
There has been another "cook" build system that was first made available in the early 2000's by a notable software author, Peter Miller. Your system seems to share no relationship with it and that may be confusing for some users.

http://ibiblio.org/pub/Linux/devel/make/cook-2.25.tut.pdf
https://en.wikipedia.org/wiki/Peter_Miller_(software_engineer)
https://lists.auug.org.au/pipermail/cook-users/

I would recommend choosing another name, or including prominent footnotes indicating that there is no relationship in respect to that prior author's work.

**Comment by bovine** [comment]
I see this was also mentioned in issue #1 so I'm not the only one with this concern.

**Comment by jachris** [comment]
Hello, thank you for taking the time to open this issue. This project is currently not in active development. However, I take this issue seriously and I will try to find an appropriate solution if and when I continue this project one day. Thank you for your patience until then.
